@Library('shared-library') _

pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "nourhanosama/flask-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Build Image') {
            steps {
                script {
                    buildImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Scan Image') {
            steps {
                script {
                    scanImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Push Image') {
            steps {
                script {
                    pushImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Remove Local Image') {
            steps {
                script {
                    removeImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Deploy on K8s') {
            steps {
                script {
                    deployOnK8s(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
    }
}
