@Library('shared-library') _

pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "nourhanosama/flask-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Build Image') {
            steps {
                script {
                    buildDockerImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Scan Image') {
            steps {
                script {
                    scanDockerImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Push Image') {
            steps {
                script {
                    pushDockerImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Delete Image Locally') {
            steps {
                script {
                    deleteLocalImage(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Update Manifests') {
            steps {
                script {
                    updateK8sManifests(DOCKER_IMAGE, IMAGE_TAG)
                }
            }
        }
        
        stage('Push Manifests') {
            steps {
                script {
                    pushManifests()
                }
            }
        }
    }
}
